export const READ_ERROR = 'READ_ERROR'

export const OPEN_UI = 'OPEN_UI'
export const CLOSE_UI = 'CLOSE_UI'
export const TOGGLE = 'TOGGLE'

export const GET_EMAILS_F_REQUEST = 'GET_EMAILS_F_REQUEST'
export const GET_EMAILS_F_SUCCESS = 'GET_EMAILS_F_SUCCESS'
export const GET_EMAILS_F_FAILURE = 'GET_EMAILS_F_FAILURE'
export const GET_EMAILS_F_CANCEL = 'GET_EMAILS_F_CANCEL'
export const GET_EMAILS_REQUEST = 'GET_EMAILS_REQUEST'
export const GET_EMAILS_SUCCESS = 'GET_EMAILS_SUCCESS'
export const GET_EMAILS_FAILURE = 'GET_EMAILS_FAILURE'
